
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Himanshu
 */
public class Check_fare_availability extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    Statement stmt;
    public String user;
    public String password;
    public Check_fare_availability(String user,String password) {
        initComponents();
        this.user=user;
        this.password=password;
        jTextField2.setVisible(false);
        jDateChooser1.setVisible(false);
        jLabel6.setText("<html><U>Check Availability & Fare</U></html>");
        jPanel1.setVisible(false);
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            //JOptionPane.showMessageDialog(this,"Driver Loaded...");
            try
            {
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","oracle");
                //JOptionPane.showMessageDialog(null,"Connection Established...");
            }
            catch(SQLException ex)
            {
                //System.out.println("Connection Not Established");
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex)
        {
            //System.out.println("Driver Not Loaded");
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Train Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Departure Time");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Arrival Time");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Duration");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Check Availability & Fare");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Check Availability & Fare");

        jTextField1.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("jLabel9");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Date Selected : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Availablity : ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total Fare : ");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);

        jTextField4.setEditable(false);

        jTextField5.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Classes", "AC First Class", "AC 2 Tier", "First Class", "AC 3 Tier", "Sleeper", "General" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Class");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(443, 443, 443)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)))
                        .addGap(96, 96, 96)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //select_train sete = new select_train();
        Date date = jDateChooser1.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
        String strDate= formatter.format(date);
        try
        {
            String sql = "Select * from book where t_name ='"+jTextField1.getText()+"' and date_of_jorney = '"+strDate+"'";
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next())
            {
                jTextField3.setText(""+strDate);
                jPanel1.setVisible(true);
                if(jComboBox1.getSelectedIndex()==1)
                {
                    jTextField4.setText(""+rs.getString(6));
                    jTextField5.setText(""+rs.getString(10));        
                }
                else if(jComboBox1.getSelectedIndex()==2)
                {
                    jTextField4.setText(""+rs.getString(4));
                    jTextField5.setText(""+rs.getString(11));
                }
                else if(jComboBox1.getSelectedIndex()==3)
                {
                    jTextField4.setText(""+rs.getString(7));
                    jTextField5.setText(""+rs.getString(13)); 
                }
                else if(jComboBox1.getSelectedIndex()==4)
                {
                    jTextField4.setText(""+rs.getString(5));
                    jTextField5.setText(""+rs.getString(12)); 
                }
                else if(jComboBox1.getSelectedIndex()==5)
                {
                    jTextField4.setText(""+rs.getString(8));
                    jTextField5.setText(""+rs.getString(14));
                }
                else if(jComboBox1.getSelectedIndex()==6)
                {
                    jTextField4.setText(""+rs.getString(9));
                    jTextField5.setText(""+rs.getString(15));   
                }
                else
                {
                    jPanel1.setVisible(false);
                    JOptionPane.showMessageDialog(null,"Please select any class!!!");
                }
            }
            else
            {
                try
                {
                    String sql2 = "Select * from train_deatails where t_name ='"+jTextField1.getText()+"'";
                    stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    ResultSet rs1 = stmt.executeQuery(sql2);
                    if(rs1.next())
                    {
                        jTextField3.setText(""+strDate);
                        jPanel1.setVisible(true);
                        if(jComboBox1.getSelectedIndex()==1)
                        {
                            jTextField4.setText(""+rs1.getString(11));
                            jTextField5.setText(""+rs1.getString(16));        
                        }
                        else if(jComboBox1.getSelectedIndex()==2)
                        {
                            jTextField4.setText(""+rs1.getString(9));
                            jTextField5.setText(""+rs1.getString(17));
                        }
                        else if(jComboBox1.getSelectedIndex()==3)
                        {
                            jTextField4.setText(""+rs1.getString(12));
                            jTextField5.setText(""+rs1.getString(18)); 
                        }
                        else if(jComboBox1.getSelectedIndex()==4)
                        {
                            jTextField4.setText(""+rs1.getString(10));
                            jTextField5.setText(""+rs1.getString(19)); 
                        }
                        else if(jComboBox1.getSelectedIndex()==5)
                        {
                            jTextField4.setText(""+rs1.getString(13));
                            jTextField5.setText(""+rs1.getString(20));
                        }
                        else if(jComboBox1.getSelectedIndex()==6)
                        {
                            jTextField4.setText(""+rs1.getString(14));
                            jTextField5.setText(""+rs1.getString(21));   
                        }
                        else
                        {
                            jPanel1.setVisible(false);
                            JOptionPane.showMessageDialog(null,"Please select any class!!!");
                        }    
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            int avail = Integer.parseInt(jTextField4.getText());
            if(avail<=0)
            {
                JOptionPane.showMessageDialog(null,"Seats are not available for this class!!!! \n      Change the Date or class");
            }
            else
            {
                Add_passenger add = new Add_passenger(jLabel7.getText(),jLabel8.getText(),jLabel9.getText(),user,password);
                String a = jComboBox1.getSelectedItem().toString();
                add.setVisible(true);
                Date date = jDateChooser1.getDate();
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
                String strDate= formatter.format(date);
                add.jTextField16.setText(a);
                add.jTextField12.setText(jTextField5.getText());
                add.jTextField13.setText(jTextField3.getText());
                add.jTextField14.setText(jTextField4.getText());
                add.jTextField15.setText(jTextField1.getText());
                try
                {
                    String sql2 = "Select * from book where t_name ='"+jTextField1.getText()+"' and date_of_jorney = '"+strDate+"'";
                    stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    ResultSet rs1 = stmt.executeQuery(sql2);
                    if(rs1.next() && rs1.getString(3).equals("true"))
                    {        
                        String sql1 = "Insert into book  values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                        ps=con.prepareStatement(sql1);
                        ps.setString(1,jTextField1.getText());
                        ps.setString(2, strDate);
                        ps.setString(3,"false");
                        ps.setString(4,rs1.getString(4));
                        ps.setString(5,rs1.getString(5));
                        ps.setString(6,rs1.getString(6));
                        ps.setString(7,rs1.getString(7));
                        ps.setString(8,rs1.getString(8));
                        ps.setString(9,rs1.getString(9));
                        ps.setString(10,rs1.getString(10));
                        ps.setString(11,rs1.getString(11));
                        ps.setString(12,rs1.getString(12));
                        ps.setString(13,rs1.getString(13));
                        ps.setString(14,rs1.getString(14));
                        ps.setString(15,rs1.getString(15));
                        if(jComboBox1.getSelectedIndex()==1)
                        {
                            ps.setString(16,jComboBox1.getSelectedItem().toString());
                        }
                        else if(jComboBox1.getSelectedIndex()==2)
                        {                        
                            ps.setString(16,jComboBox1.getSelectedItem().toString());
                        }
                        else if(jComboBox1.getSelectedIndex()==3)
                        {                        
                            ps.setString(16,jComboBox1.getSelectedItem().toString());
                        }
                        else if(jComboBox1.getSelectedIndex()==4)
                        {                       
                            ps.setString(16,jComboBox1.getSelectedItem().toString());
                        }
                        else if(jComboBox1.getSelectedIndex()==5)
                        {
                            ps.setString(16,jComboBox1.getSelectedItem().toString());
                        }
                        else if(jComboBox1.getSelectedIndex()==6)
                        { 
                            ps.setString(16,jComboBox1.getSelectedItem().toString());
                        }
                        else
                        {
                            ps.setString(16," ");
                        }   
                        String sql3 = "delete from book where t_name ='"+jTextField1.getText()+"' and date_of_jorney = '"+strDate+"'";
                        PreparedStatement ps2=con.prepareStatement(sql3);
                        ps2.execute();
                        
                        ps.execute();
                    }
                    else if(rs1.next() && rs1.getString(3).equals("false"))
                    {
                        System.out.print("DO Nothing");
                    }
                    else
                    {
                        String sql5 = "select * from train_deatails where t_name = '"+jTextField1.getText()+"'";
                        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                        ResultSet rs4 = stmt.executeQuery(sql5);
                        if(rs4.next())
                        {
                            String sql6 = "Insert into book  values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                            PreparedStatement ps5  = con.prepareStatement(sql6);
                            ps5.setString(1,jTextField1.getText());
                            ps5.setString(2,strDate);
                            ps5.setString(3,"false");
                            ps5.setString(4,rs4.getString(9));
                            ps5.setString(5,rs4.getString(10));
                            ps5.setString(6,rs4.getString(11));
                            ps5.setString(7,rs4.getString(12));
                            ps5.setString(8,rs4.getString(13));
                            ps5.setString(9,rs4.getString(14));
                            ps5.setString(10,rs4.getString(16));
                            ps5.setString(11,rs4.getString(17));
                            ps5.setString(12,rs4.getString(19));
                            ps5.setString(13,rs4.getString(18));
                            ps5.setString(14,rs4.getString(20));
                            ps5.setString(15,rs4.getString(21));
                            ps5.setString(16,a);
                            ps5.execute();
                        }
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      Date date = jDateChooser1.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
        String strDate= formatter.format(date);
        try
        {
            String sql = "Select * from book where t_name ='"+jTextField1.getText()+"' and date_of_jorney = '"+strDate+"'";
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next())
            {
                jTextField3.setText(""+strDate);
                //jPanel1.setVisible(true);
                if(jComboBox1.getSelectedIndex()==1)
                {
                    jTextField4.setText(""+rs.getString(6));
                    jTextField5.setText(""+rs.getString(10));        
                }
                else if(jComboBox1.getSelectedIndex()==2)
                {
                    jTextField4.setText(""+rs.getString(4));
                    jTextField5.setText(""+rs.getString(11));
                }
                else if(jComboBox1.getSelectedIndex()==3)
                {
                    jTextField4.setText(""+rs.getString(7));
                    jTextField5.setText(""+rs.getString(13)); 
                }
                else if(jComboBox1.getSelectedIndex()==4)
                {
                    jTextField4.setText(""+rs.getString(5));
                    jTextField5.setText(""+rs.getString(12)); 
                }
                else if(jComboBox1.getSelectedIndex()==5)
                {
                    jTextField4.setText(""+rs.getString(8));
                    jTextField5.setText(""+rs.getString(14));
                }
                else if(jComboBox1.getSelectedIndex()==6)
                {
                    jTextField4.setText(""+rs.getString(9));
                    jTextField5.setText(""+rs.getString(15));   
                }
                else
                {
                    jPanel1.setVisible(false);
                    JOptionPane.showMessageDialog(null,"Please select any class!!!");
                }
            }
            else
            {
                try
                {
                    String sql2 = "Select * from train_deatails where t_name ='"+jTextField1.getText()+"'";
                    stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    ResultSet rs1 = stmt.executeQuery(sql2);
                    if(rs1.next())
                    {
                        jTextField3.setText(""+strDate);
                        //jPanel1.setVisible(true);
                        if(jComboBox1.getSelectedIndex()==1)
                        {
                            jTextField4.setText(""+rs1.getString(11));
                            jTextField5.setText(""+rs1.getString(16));        
                        }
                        else if(jComboBox1.getSelectedIndex()==2)
                        {
                            jTextField4.setText(""+rs1.getString(9));
                            jTextField5.setText(""+rs1.getString(17));
                        }
                        else if(jComboBox1.getSelectedIndex()==3)
                        {
                            jTextField4.setText(""+rs1.getString(12));
                            jTextField5.setText(""+rs1.getString(18)); 
                        }
                        else if(jComboBox1.getSelectedIndex()==4)
                        {
                            jTextField4.setText(""+rs1.getString(10));
                            jTextField5.setText(""+rs1.getString(19)); 
                        }
                        else if(jComboBox1.getSelectedIndex()==5)
                        {
                            jTextField4.setText(""+rs1.getString(13));
                            jTextField5.setText(""+rs1.getString(20));
                        }
                        else if(jComboBox1.getSelectedIndex()==6)
                        {
                            jTextField4.setText(""+rs1.getString(14));
                            jTextField5.setText(""+rs1.getString(21));   
                        }
                        else
                        {
                            jPanel1.setVisible(false);
                            JOptionPane.showMessageDialog(null,"Please select any class!!!");
                        }    
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_fare_availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_fare_availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_fare_availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_fare_availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_fare_availability(null,null).setVisible(true);
            }
        });
    }private static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JComboBox<String> jComboBox1;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
