import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Himanshu
 */
public class Print_ticket extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    PreparedStatement ps1;
    Statement stmt;
    public String t_name;
    public String Class_selected;
    public String date_of_jorney;
    public String count;
    public String user;
    public String password;
    public String name,age,class_selected,seat_number;
    public Print_ticket(String t_name,String Class_selected,String date_of_jorney,String count,String user,String password,String name,String age,String class_selected,String seat_number) {
        initComponents();
        this.t_name = t_name;
        this.Class_selected=Class_selected;
        this.date_of_jorney=date_of_jorney;
        this.count=count;      
        this.user=user;
        this.password=password;
        this.name=name;
        this.age=age;
        this.class_selected=class_selected;
        this.seat_number=seat_number;
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            //JOptionPane.showMessageDialog(this,"Driver Loaded...");
            try
            {
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","oracle");
                //JOptionPane.showMessageDialog(null,"Connection Established...");
            }
            catch(SQLException ex)
            {
                System.out.println("Connection Not Established");
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex)
        {
            System.out.println("Driver Not Loaded");
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Print Your Ticket");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Book Another Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton2)
                .addGap(41, 160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            System.out.print(user);
            System.out.print(password);
            try
            {
                jTextArea1.print();
            }
            catch(PrinterException e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            
            
            int count1 = Integer.parseInt(count);
            try
            {
                String sql1 = "select * from book where t_name = '"+t_name+"' and class_selected = '"+Class_selected+"' and date_of_jorney = '"+date_of_jorney+"' and payment_status='true'";
                Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE); 
                ResultSet rs = st.executeQuery(sql1);
                if(rs.next())
                {
                    String a = rs.getString(6);
                    int g =Integer.parseInt(a)-count1;
                    String b = rs.getString(4);
                    int h =Integer.parseInt(b)-count1;
                    String c = rs.getString(5);
                    int i =Integer.parseInt(c)-count1;
                    String d = rs.getString(7);
                    int j =Integer.parseInt(d)-count1;
                    String e= rs.getString(8);
                    int k =Integer.parseInt(e)-count1;
                    String f = rs.getString(9);
                    int l =Integer.parseInt(f)-count1;
                    
                    if(Class_selected.equals("AC First Class"))
                    {
                        String sql2 = "Update book set no_acfirstclass = '"+g+"'";
                        ps=con.prepareStatement(sql2);
                        ps.executeUpdate();
                    }
                    else if(Class_selected.equals("AC 2 Tier"))
                    {
                        String sql2 = "Update book set no_ac2tier = '"+h+"'";
                        ps=con.prepareStatement(sql2);
                        ps.executeUpdate();
                    }
                    else if(Class_selected.equals("AC 3 Tier"))
                    {
                        String sql2 = "Update book set no_ac3tier = '"+i+"'";
                        ps=con.prepareStatement(sql2);
                        ps.executeUpdate();
                    }
                    else if(Class_selected.equals("First Class"))
                    {
                        String sql2 = "Update book set no_firstclass = '"+j+"'";
                        ps=con.prepareStatement(sql2);
                        ps.executeUpdate();
                    }
                    else if(Class_selected.equals("Sleeper"))
                    {
                        String sql2 = "Update book set no_sleeper = '"+k+"'";
                        ps=con.prepareStatement(sql2);
                        ps.executeUpdate();
                    }
                    else if(Class_selected.equals("General"))
                    {
                        String sql2 = "Update book set no_general = '"+l+"'";
                        ps=con.prepareStatement(sql2);
                        ps.executeUpdate();
                    }
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            
            try
            {
                String sql3  ="delete from passenger_deatails";
                ps=con.prepareStatement(sql3);
                ps.execute();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int yesorno = JOptionPane.showConfirmDialog(null,"Do you want to book another ticket","Proceed",JOptionPane.YES_NO_OPTION);
        if(yesorno==0)
        {
            Login sete = new Login(name,age,class_selected,seat_number);
            dispose();
            sete.setVisible(true);
        }
        else
        {
            System.exit(0);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_ticket(null,null,null,null,null,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
